/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appointmentcalendar;

/**
 *
 * @author Pir8
 */
public class accountLoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form accountLogin
     */
    public accountLoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        theAppointmentSchedulerTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        signInButton = new javax.swing.JButton();
        createNewAccountButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        theAppointmentSchedulerTitle.setFont(new java.awt.Font("Copperplate", 0, 24)); // NOI18N
        theAppointmentSchedulerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        theAppointmentSchedulerTitle.setText("THE APPOINTMENT SCHEDULER");
        getContentPane().add(theAppointmentSchedulerTitle);
        theAppointmentSchedulerTitle.setBounds(135, 18, 405, 58);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EMAIL ADDRESS");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(147, 82, 110, 16);

        emailText.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        getContentPane().add(emailText);
        emailText.setBounds(147, 104, 357, 21);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(155, 148, 68, 16);

        jTextField1.setToolTipText("");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(147, 170, 357, 22);

        signInButton.setText("SIGN IN");
        getContentPane().add(signInButton);
        signInButton.setBounds(409, 253, 77, 25);

        createNewAccountButton.setText("CREATE A NEW ACCOUNT");
        getContentPane().add(createNewAccountButton);
        createNewAccountButton.setBounds(155, 253, 183, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appointmentcalendar/xHospital-wallpaper.jpg.pagespeed.ic.EBB6AIGoe3.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-5, 0, 680, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accountLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accountLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accountLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accountLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accountLoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createNewAccountButton;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton signInButton;
    private javax.swing.JLabel theAppointmentSchedulerTitle;
    // End of variables declaration//GEN-END:variables
}
